version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - internal
      
  drupal1:
    image: drupal:8.7.8-fpm-alpine
    container_name: drupal1
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - internal
      - external
    volumes:
      - drupal-data:/var/www/html
      
   drupal2:
    image: drupal:8.7.8-fpm-alpine
    container_name: drupal2
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - internal
      - external
    volumes:
      - drupal-data:/var/www/html

  LoadBalancer:
  
    build: ./load-balancer
    tty: true
    links: 
         - drupal1
         - drupal2
    ports: 
         - '8080:8080'
